
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { StaffMember } from '../types';

export interface PayslipData {
    period: string; // e.g. "January 2026"
    payDate: string;
    staff: StaffMember;
    earnings: {
        regularHours: number;
        overtimeHours: number;
        regularAmount: number;
        overtimeAmount: number;
        grossPay: number;
    };
    deductions: {
        tax: number;
        ni: number;
        pension: number;
        advance: number;
        total: number;
    };
    netPay: number;
}

export const generatePayslip = (data: PayslipData) => {
    const doc = new jsPDF();

    // --- HEADER ---
    doc.setFillColor(33, 33, 33); // Dark Gray Banner
    doc.rect(0, 0, 210, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text("ENGLABS INVENTORY", 105, 20, { align: "center" }); // Centered

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    // doc.text("Private & Confidential", 105, 30, { align: "center" });

    // --- DETAILS ---
    doc.setTextColor(40, 40, 40);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');

    // Left Column: Employee
    doc.text("EMPLOYEE DETAILS", 14, 55);
    doc.setDrawColor(200, 200, 200);
    doc.line(14, 57, 80, 57);

    doc.setFont('helvetica', 'normal');
    doc.text(`Name: ${data.staff.name.toUpperCase()}`, 14, 65);
    doc.text(`Role: ${data.staff.role}`, 14, 71);
    doc.text(`ID: ${data.staff.id.slice(0, 8)}`, 14, 77);
    doc.text(`Tax Code: ${data.staff.taxCode || '1257L'}`, 14, 83);
    doc.text(`NI Number: ${data.staff.niNumber || 'Pending'}`, 14, 89);

    // Right Column: Pay Period
    doc.setFont('helvetica', 'bold');
    doc.text("PAY PERIOD", 130, 55);
    doc.line(130, 57, 196, 57);

    doc.setFont('helvetica', 'normal');
    doc.text(`Period: ${data.period}`, 130, 65);
    doc.text(`Pay Date: ${data.payDate}`, 130, 71);

    // --- EARNINGS TABLE ---
    const hourlyRate = data.staff.hourlyRate || 0;
    const otRate = hourlyRate * 1.5;

    autoTable(doc, {
        startY: 100,
        head: [['EARNINGS', 'HOURS', 'RATE', 'AMOUNT']],
        body: [
            ['Basic Pay', data.earnings.regularHours.toFixed(2), `£${hourlyRate.toFixed(2)}`, `£${data.earnings.regularAmount.toFixed(2)}`],
            ...(data.earnings.overtimeHours > 0 ? [['Overtime (1.5x)', data.earnings.overtimeHours.toFixed(2), `£${otRate.toFixed(2)}`, `£${data.earnings.overtimeAmount.toFixed(2)}`]] : []),
        ],
        foot: [['Total Gross Pay', '', '', `£${data.earnings.grossPay.toFixed(2)}`]],
        theme: 'grid',
        headStyles: { fillColor: [56, 56, 56], textColor: [255, 255, 255], fontStyle: 'bold' },
        footStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0], fontStyle: 'bold', halign: 'right' },
        columnStyles: {
            0: { cellWidth: 80 },
            3: { halign: 'right' }
        },
        margin: { top: 10 }
    });

    // --- DEDUCTIONS TABLE ---
    const finalY = (doc as any).lastAutoTable.finalY + 15;

    autoTable(doc, {
        startY: finalY,
        head: [['DEDUCTIONS', 'AMOUNT']],
        body: [
            ['Income Tax', `£${data.deductions.tax.toFixed(2)}`],
            ['National Insurance', `£${data.deductions.ni.toFixed(2)}`],
            ['Pension (3%)', `£${data.deductions.pension.toFixed(2)}`],
            ...(data.deductions.advance > 0 ? [['Advance Repayment', `£${data.deductions.advance.toFixed(2)}`]] : []),
        ],
        foot: [['Total Deductions', `£${data.deductions.total.toFixed(2)}`]],
        theme: 'grid',
        headStyles: { fillColor: [180, 50, 50], textColor: [255, 255, 255], fontStyle: 'bold' }, // Red for deductions
        footStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0], fontStyle: 'bold', halign: 'right' },
        columnStyles: {
            1: { halign: 'right' } // Align Amount Right
        }
    });

    // --- NET PAY ---
    const netY = (doc as any).lastAutoTable.finalY + 20;

    doc.setFillColor(236, 253, 245); // Emerald 50
    doc.setDrawColor(16, 185, 129); // Emerald 500
    doc.roundedRect(130, netY, 66, 25, 3, 3, 'FD');

    doc.setFontSize(10);
    doc.setTextColor(16, 185, 129); // Emerald 500
    doc.text("NET PAY", 163, netY + 8, { align: "center" });

    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(6, 95, 70); // Emerald 900
    doc.text(`£${data.netPay.toFixed(2)}`, 163, netY + 18, { align: "center" });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by ENGLABS Command OS", 105, 290, { align: "center" });

    doc.save(`Payslip_${data.staff.name.replace(' ', '_')}_${data.period}.pdf`);
};
