/**
 * 🛰️ Auto-Generated Seed Data from Excel
 * Date: 21/4/2026, 6:03:00 pm
 */

export const EXCEL_SEED = {
    ledger: [
    {
        "type": "OUT",
        "amount": 2731,
        "date": "2026-04-01T00:00:00.000Z",
        "description": "Last Month Balance ",
        "project": "C-GENERAL",
        "category": "GENERAL",
        "from": " ",
        "mode": " ",
        "recBy": " ",
        "balance": -2731,
        "ref": "EX-ROW-4"
    },
    {
        "type": "IN",
        "amount": 5000,
        "date": "2026-04-02T00:00:00.000Z",
        "description": "Purchase to TV Stand For delhi Expo",
        "project": "C-GENERAL",
        "category": "EMERGENCY",
        "from": "Englabs IDFC",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "balance": -2581,
        "ref": "EX-ROW-5"
    },
    {
        "type": "OUT",
        "amount": 4850,
        "date": "2026-04-02T00:00:00.000Z",
        "description": "Purchase to TV Stand For delhi Expo",
        "project": "C-GENERAL",
        "category": "EMERGENCY",
        "from": "Englabs IDFC",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "balance": -2581,
        "ref": "EX-ROW-5"
    },
    {
        "type": "IN",
        "amount": 10000,
        "date": "2026-04-02T00:00:00.000Z",
        "description": "Purchase to Bondtite and Favikwik   For delhi Expo",
        "project": "C-GENERAL",
        "category": "EMERGENCY",
        "from": "Englabs IDFC",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "balance": 6569,
        "ref": "EX-ROW-6"
    },
    {
        "type": "OUT",
        "amount": 850,
        "date": "2026-04-02T00:00:00.000Z",
        "description": "Purchase to Bondtite and Favikwik   For delhi Expo",
        "project": "C-GENERAL",
        "category": "EMERGENCY",
        "from": "Englabs IDFC",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "balance": 6569,
        "ref": "EX-ROW-6"
    },
    {
        "type": "IN",
        "amount": 5000,
        "date": "2026-04-02T00:00:00.000Z",
        "description": "UPI Rohit verma   For delhi Expo",
        "project": "C-GENERAL",
        "category": "EMERGENCY",
        "from": "Englabs IDFC",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "balance": 11469,
        "ref": "EX-ROW-7"
    },
    {
        "type": "OUT",
        "amount": 100,
        "date": "2026-04-02T00:00:00.000Z",
        "description": "UPI Rohit verma   For delhi Expo",
        "project": "C-GENERAL",
        "category": "EMERGENCY",
        "from": "Englabs IDFC",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "balance": 11469,
        "ref": "EX-ROW-7"
    },
    {
        "type": "OUT",
        "amount": 3200,
        "date": "2026-04-02T00:00:00.000Z",
        "description": "Printer Repair Sky5 ",
        "project": "C-GENERAL",
        "category": "MAINTENANCE",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 8269,
        "ref": "EX-ROW-8"
    },
    {
        "type": "OUT",
        "amount": 250,
        "date": "2026-04-02T00:00:00.000Z",
        "description": "Porter From Raj Enterprices to Englabs For Delhi Expo. (TV STAND)",
        "project": "C-GENERAL",
        "category": "EMERGENCY",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 8019,
        "ref": "EX-ROW-9"
    },
    {
        "type": "OUT",
        "amount": 1475,
        "date": "2026-04-02T00:00:00.000Z",
        "description": "Porter From Faridabad to  Bajaj  (C5033)",
        "project": "C5033",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 6544,
        "ref": "EX-ROW-10"
    },
    {
        "type": "OUT",
        "amount": 270,
        "date": "2026-04-03T00:00:00.000Z",
        "description": "Porter From Fixpro to Airport Expo Delhi",
        "project": "C-GENERAL",
        "category": "EMERGENCY",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 6274,
        "ref": "EX-ROW-11"
    },
    {
        "type": "OUT",
        "amount": 500,
        "date": "2026-04-03T00:00:00.000Z",
        "description": "Aebocode Visit Shubham Expo Delhi",
        "project": "C-GENERAL",
        "category": "EMERGENCY",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 5774,
        "ref": "EX-ROW-12"
    },
    {
        "type": "OUT",
        "amount": 70,
        "date": "2026-04-04T00:00:00.000Z",
        "description": "Purchased to Panchkula graphics (Stickers) For Delhi Expo by Devanshu  ",
        "project": "C-GENERAL",
        "category": "EMERGENCY",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 5704,
        "ref": "EX-ROW-13"
    },
    {
        "type": "OUT",
        "amount": 400,
        "date": "2026-04-04T00:00:00.000Z",
        "description": "Porter From Chennai Airport to Hankl C5008",
        "project": "C5008",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 5304,
        "ref": "EX-ROW-14"
    },
    {
        "type": "OUT",
        "amount": 111,
        "date": "2026-04-04T00:00:00.000Z",
        "description": "Porter From Englabs to  Goel  C4929",
        "project": "C4929",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 5193,
        "ref": "EX-ROW-15"
    },
    {
        "type": "OUT",
        "amount": 70,
        "date": "2026-04-04T00:00:00.000Z",
        "description": "Purchase to Extension Fuse C4465",
        "project": "C4465",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 5123,
        "ref": "EX-ROW-16"
    },
    {
        "type": "OUT",
        "amount": 450,
        "date": "2026-04-04T00:00:00.000Z",
        "description": "Purchsed to Glash for Medical Device Expo Delhi",
        "project": "C-GENERAL",
        "category": "EMERGENCY",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 4673,
        "ref": "EX-ROW-17"
    },
    {
        "type": "OUT",
        "amount": 210,
        "date": "2026-04-06T00:00:00.000Z",
        "description": "Porter From Ultra Spark to Enertics  C4851",
        "project": "c4851",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 4463,
        "ref": "EX-ROW-18"
    },
    {
        "type": "OUT",
        "amount": 180,
        "date": "2026-04-06T00:00:00.000Z",
        "description": "Porter From SK Techno to Hella Metal C5010",
        "project": "C5010",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 4283,
        "ref": "EX-ROW-19"
    },
    {
        "type": "OUT",
        "amount": 320,
        "date": "2026-04-06T00:00:00.000Z",
        "description": "Porter From Fix Pro to Airport Expo Delhi",
        "project": "C-GENERAL",
        "category": "EMERGENCY",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 3963,
        "ref": "EX-ROW-20"
    },
    {
        "type": "OUT",
        "amount": 280,
        "date": "2026-04-06T00:00:00.000Z",
        "description": "Porter From Henkel telekar to Airport C5008",
        "project": "C5008",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 3683,
        "ref": "EX-ROW-21"
    },
    {
        "type": "OUT",
        "amount": 1770,
        "date": "2026-04-06T00:00:00.000Z",
        "description": "Purchesed to Scrow For Delhi Expo ",
        "project": "C-GENERAL",
        "category": "EMERGENCY",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 1913,
        "ref": "EX-ROW-22"
    },
    {
        "type": "OUT",
        "amount": 400,
        "date": "2026-04-07T00:00:00.000Z",
        "description": "Porter From Rohit sir PA11 to Endureair C5098",
        "project": "C5098",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 1513,
        "ref": "EX-ROW-23"
    },
    {
        "type": "OUT",
        "amount": 72,
        "date": "2026-04-07T00:00:00.000Z",
        "description": "Porter From Enertics to Englabs by Anurag C4851",
        "project": "C5098",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 1441,
        "ref": "EX-ROW-24"
    },
    {
        "type": "OUT",
        "amount": 500,
        "date": "2026-04-07T00:00:00.000Z",
        "description": "RO Service + Candale Charge ",
        "project": "C-GENERAL",
        "category": "MAINTENANCE",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 941,
        "ref": "EX-ROW-25"
    },
    {
        "type": "OUT",
        "amount": 180,
        "date": "2026-04-07T00:00:00.000Z",
        "description": "Porter From Plastipack to 3D Paradise. C5108",
        "project": "C5108",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 761,
        "ref": "EX-ROW-26"
    },
    {
        "type": "OUT",
        "amount": 1138,
        "date": "2026-04-07T00:00:00.000Z",
        "description": "Purchase to Delhot Expo Materials ",
        "project": "C-GENERAL",
        "category": "EMERGENCY",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": -377,
        "ref": "EX-ROW-27"
    },
    {
        "type": "OUT",
        "amount": 300,
        "date": "2026-04-07T00:00:00.000Z",
        "description": "Porter  Talekar to Pune Airport C5008",
        "project": "C5008",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": -677,
        "ref": "EX-ROW-28"
    },
    {
        "type": "OUT",
        "amount": 197,
        "date": "2026-04-08T00:00:00.000Z",
        "description": "Blinkit UPI",
        "project": "C-GENERAL",
        "category": "LOGISTICS",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": -874,
        "ref": "EX-ROW-29"
    },
    {
        "type": "OUT",
        "amount": 550,
        "date": "2026-04-08T00:00:00.000Z",
        "description": "Porter From Channai to Henkel C5008",
        "project": "C5008",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": -1424,
        "ref": "EX-ROW-30"
    },
    {
        "type": "OUT",
        "amount": 150,
        "date": "2026-04-08T00:00:00.000Z",
        "description": "Porter From ITL to Zirakpur C5090",
        "project": "C5090",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": -1574,
        "ref": "EX-ROW-31"
    },
    {
        "type": "OUT",
        "amount": 290,
        "date": "2026-04-08T00:00:00.000Z",
        "description": "Porter From Talekar to Pune Airport C5092",
        "project": "C5092",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": -1864,
        "ref": "EX-ROW-32"
    },
    {
        "type": "OUT",
        "amount": 224,
        "date": "2026-04-09T00:00:00.000Z",
        "description": "Sai Dairy Milk Last Bill Full & Final",
        "project": "C-GENERAL",
        "category": "LOGISTICS",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": -2088,
        "ref": "EX-ROW-33"
    },
    {
        "type": "OUT",
        "amount": 260,
        "date": "2026-04-09T00:00:00.000Z",
        "description": "Porter From Adoroitec to AV Machining C5014",
        "project": "C-GENERAL",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": -2348,
        "ref": "EX-ROW-34"
    },
    {
        "type": "IN",
        "amount": 5000,
        "date": "2026-04-10T00:00:00.000Z",
        "description": "Milk 4 nos + 2 Sunday by Arjun ",
        "project": "C-GENERAL",
        "category": "LOGISTICS",
        "from": "Englabs IDFC",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "balance": 2460,
        "ref": "EX-ROW-35"
    },
    {
        "type": "OUT",
        "amount": 192,
        "date": "2026-04-10T00:00:00.000Z",
        "description": "Milk 4 nos + 2 Sunday by Arjun ",
        "project": "C-GENERAL",
        "category": "LOGISTICS",
        "from": "Englabs IDFC",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "balance": 2460,
        "ref": "EX-ROW-35"
    },
    {
        "type": "OUT",
        "amount": 704,
        "date": "2026-04-11T00:00:00.000Z",
        "description": "Blinkit UPI",
        "project": "C-GENERAL",
        "category": "LOGISTICS",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 1756,
        "ref": "EX-ROW-36"
    },
    {
        "type": "OUT",
        "amount": 350,
        "date": "2026-04-11T00:00:00.000Z",
        "description": "Porter From Channai to Henkel C5092",
        "project": "C5092",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 1406,
        "ref": "EX-ROW-37"
    },
    {
        "type": "OUT",
        "amount": 400,
        "date": "2026-04-11T00:00:00.000Z",
        "description": "Porter From Sonalika Delhi to Chandigarh C5131",
        "project": "C5131",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 1006,
        "ref": "EX-ROW-38"
    },
    {
        "type": "OUT",
        "amount": 130,
        "date": "2026-04-12T00:00:00.000Z",
        "description": "Porter From Tribune to Englabs ITL C5131",
        "project": "C5131",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 876,
        "ref": "EX-ROW-39"
    },
    {
        "type": "OUT",
        "amount": 167,
        "date": "2026-04-13T00:00:00.000Z",
        "description": "Blinkit UPI",
        "project": "C-GENERAL",
        "category": "LOGISTICS",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 709,
        "ref": "EX-ROW-40"
    },
    {
        "type": "IN",
        "amount": 10000,
        "date": "2026-04-14T00:00:00.000Z",
        "description": "Porter  From Excel to Marelli C4925",
        "project": "C4925",
        "category": "GENERAL",
        "from": "Englabs IDFC",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "balance": 10389,
        "ref": "EX-ROW-41"
    },
    {
        "type": "OUT",
        "amount": 320,
        "date": "2026-04-14T00:00:00.000Z",
        "description": "Porter  From Excel to Marelli C4925",
        "project": "C4925",
        "category": "GENERAL",
        "from": "Englabs IDFC",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "balance": 10389,
        "ref": "EX-ROW-41"
    },
    {
        "type": "OUT",
        "amount": 2080,
        "date": "2026-04-14T00:00:00.000Z",
        "description": "Porter From Faridabad to AV Machining Pune. C5014",
        "project": "C5014",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 8309,
        "ref": "EX-ROW-42"
    },
    {
        "type": "OUT",
        "amount": 390,
        "date": "2026-04-14T00:00:00.000Z",
        "description": "Porter From Plastipack to Henkel C5110",
        "project": "C5110",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 7919,
        "ref": "EX-ROW-43"
    },
    {
        "type": "OUT",
        "amount": 700,
        "date": "2026-04-14T00:00:00.000Z",
        "description": "Porter From Talekar to Pune Airport C5008",
        "project": "C5008",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 7219,
        "ref": "EX-ROW-44"
    },
    {
        "type": "OUT",
        "amount": 900,
        "date": "2026-04-14T00:00:00.000Z",
        "description": "Porter From Channai to Henkel C5008",
        "project": "C5008",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 6319,
        "ref": "EX-ROW-45"
    },
    {
        "type": "OUT",
        "amount": 730,
        "date": "2026-04-14T00:00:00.000Z",
        "description": "Verified Paytm Merchant ",
        "project": "C-GENERAL",
        "category": "MAINTENANCE",
        "from": "",
        "mode": "",
        "recBy": " ",
        "balance": 5589,
        "ref": "EX-ROW-46"
    },
    {
        "type": "IN",
        "amount": 1000,
        "date": "2026-04-14T00:00:00.000Z",
        "description": "Purchased to White Fiber SHEET + Patch  Cash",
        "project": "C-GENERAL",
        "category": "MAINTENANCE",
        "from": "Bharat sir",
        "mode": "Cash",
        "recBy": "Gaurav ",
        "balance": 5869,
        "ref": "EX-ROW-47"
    },
    {
        "type": "OUT",
        "amount": 720,
        "date": "2026-04-14T00:00:00.000Z",
        "description": "Purchased to White Fiber SHEET + Patch  Cash",
        "project": "C-GENERAL",
        "category": "MAINTENANCE",
        "from": "Bharat sir",
        "mode": "Cash",
        "recBy": "Gaurav ",
        "balance": 5869,
        "ref": "EX-ROW-47"
    },
    {
        "type": "OUT",
        "amount": 124,
        "date": "2026-04-14T00:00:00.000Z",
        "description": "Porter From CHD Paint to Englabs ",
        "project": "C-GENERAL",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 5745,
        "ref": "EX-ROW-48"
    },
    {
        "type": "OUT",
        "amount": 1000,
        "date": "2026-04-15T00:00:00.000Z",
        "description": "Zepto Account Transfer for  Milk etc",
        "project": "C-GENERAL",
        "category": "LOGISTICS",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 4745,
        "ref": "EX-ROW-49"
    },
    {
        "type": "OUT",
        "amount": 168,
        "date": "2026-04-16T00:00:00.000Z",
        "description": "Blinkit MILK UPI",
        "project": "C-GENERAL",
        "category": "LOGISTICS",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 4577,
        "ref": "EX-ROW-50"
    },
    {
        "type": "OUT",
        "amount": 2100,
        "date": "2026-04-16T00:00:00.000Z",
        "description": "Purchase to MDF SHEET 6MM & PATCH 3INCH & GITTI & RENT ",
        "project": "C-GENERAL",
        "category": "MAINTENANCE",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 2477,
        "ref": "EX-ROW-51"
    },
    {
        "type": "OUT",
        "amount": 30,
        "date": "2026-04-16T00:00:00.000Z",
        "description": "Purchase to Adrak Cash",
        "project": "C-GENERAL",
        "category": "LOGISTICS",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 2447,
        "ref": "EX-ROW-52"
    },
    {
        "type": "IN",
        "amount": 2802,
        "date": "2026-04-16T00:00:00.000Z",
        "description": "There was an error with the payment. Please check this amount and contact the Verified Accounts team.",
        "project": "C-GENERAL",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 5249,
        "ref": "EX-ROW-53"
    },
    {
        "type": "OUT",
        "amount": 1200,
        "date": "2026-04-18T00:00:00.000Z",
        "description": "Porter From Delhi to CHD C5131",
        "project": "C5131",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 4049,
        "ref": "EX-ROW-54"
    },
    {
        "type": "OUT",
        "amount": 450,
        "date": "2026-04-18T00:00:00.000Z",
        "description": "Porter From Excel to Karnal C5131",
        "project": "C5131",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 3599,
        "ref": "EX-ROW-55"
    },
    {
        "type": "OUT",
        "amount": 104,
        "date": "2026-04-18T00:00:00.000Z",
        "description": "Porter by devanshu ",
        "project": "C-GENERAL",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": " ",
        "balance": 3495,
        "ref": "EX-ROW-56"
    },
    {
        "type": "OUT",
        "amount": 1950,
        "date": "2026-04-18T00:00:00.000Z",
        "description": " Purchased to MDF Sheet 6MM & Patch half Inch & Rent ",
        "project": "C-GENERAL",
        "category": "MAINTENANCE",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 1545,
        "ref": "EX-ROW-57"
    },
    {
        "type": "OUT",
        "amount": 64,
        "date": "2026-04-19T00:00:00.000Z",
        "description": "Purchase to Milk (Sunday) Cash",
        "project": "C-GENERAL",
        "category": "LOGISTICS",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 1481,
        "ref": "EX-ROW-58"
    },
    {
        "type": "IN",
        "amount": 5000,
        "date": "2026-04-20T00:00:00.000Z",
        "description": "Purchase to Milk ) Cash",
        "project": "C-GENERAL",
        "category": "GENERAL",
        "from": "Englabs IDFC",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "balance": 6449,
        "ref": "EX-ROW-59"
    },
    {
        "type": "OUT",
        "amount": 32,
        "date": "2026-04-20T00:00:00.000Z",
        "description": "Purchase to Milk ) Cash",
        "project": "C-GENERAL",
        "category": "GENERAL",
        "from": "Englabs IDFC",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "balance": 6449,
        "ref": "EX-ROW-59"
    },
    {
        "type": "OUT",
        "amount": 152,
        "date": "2026-04-20T00:00:00.000Z",
        "description": "Porter From Techno to Delhi C5142",
        "project": "C5142",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 6297,
        "ref": "EX-ROW-60"
    },
    {
        "type": "OUT",
        "amount": 447,
        "date": "2026-04-20T00:00:00.000Z",
        "description": "Porter From Cadqua  to Rohit C5135",
        "project": "C5135",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 5850,
        "ref": "EX-ROW-61"
    },
    {
        "type": "OUT",
        "amount": 74,
        "date": "2026-04-20T00:00:00.000Z",
        "description": "Porter From Amit Bhri  to Enclosure C-….......",
        "project": "C-GENERAL",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 5776,
        "ref": "EX-ROW-62"
    },
    {
        "type": "OUT",
        "amount": 140,
        "date": "2026-04-20T00:00:00.000Z",
        "description": "Purchase to Faviquick Gel For C4950",
        "project": "C4950",
        "category": "LOGISTICS",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 5636,
        "ref": "EX-ROW-63"
    },
    {
        "type": "OUT",
        "amount": 340,
        "date": "2026-04-20T00:00:00.000Z",
        "description": "Porter From Telekar to Pune Airport C5008",
        "project": "C5008",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 5296,
        "ref": "EX-ROW-64"
    },
    {
        "type": "OUT",
        "amount": 157,
        "date": "2026-04-20T00:00:00.000Z",
        "description": "Porter From Industrial area phase to Englabs C4851",
        "project": "C4851",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 5139,
        "ref": "EX-ROW-65"
    },
    {
        "type": "OUT",
        "amount": 145,
        "date": "2026-04-21T00:00:00.000Z",
        "description": "PORTER From Englabs  to Hella Dera  bassi C4950",
        "project": "C4950",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 4994,
        "ref": "EX-ROW-66"
    },
    {
        "type": "OUT",
        "amount": 156,
        "date": "2026-04-21T00:00:00.000Z",
        "description": "cash amount",
        "project": "C-GENERAL",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 4838,
        "ref": "EX-ROW-68"
    }
],
    discoveredItems: [
    {
        "name": "TV Stand",
        "qty": 1,
        "rate": 4850
    },
    {
        "name": "Bondtite Adhesive",
        "qty": 1,
        "rate": 425
    },
    {
        "name": "Favikwik Adhesive",
        "qty": 2,
        "rate": 282.5
    },
    {
        "name": "Panchkula graphics",
        "qty": 1,
        "rate": 70
    },
    {
        "name": "Extension Fuse",
        "qty": 1,
        "rate": 70
    },
    {
        "name": "Delhot Expo Materials",
        "qty": 1,
        "rate": 1138
    },
    {
        "name": "Dairy/Office Supplies",
        "qty": 8,
        "rate": 189
    },
    {
        "name": "White Fiber SHEET + Patch  Cash",
        "qty": 1,
        "rate": 720
    },
    {
        "name": "MDF Sheets (6mm/10mm)",
        "qty": 2,
        "rate": 2025
    },
    {
        "name": "Adrak Cash",
        "qty": 1,
        "rate": 30
    }
],
    discoveredProjects: [
    "C-GENERAL",
    "C5033",
    "C5008",
    "C4929",
    "C4465",
    "c4851",
    "C5010",
    "C5098",
    "C5108",
    "C5090",
    "C5092",
    "C5131",
    "C4925",
    "C5014",
    "C5110",
    "C5142",
    "C5135",
    "C4950",
    "C4851",
    "Drone Survey"
]
};
