/**
 * 🛰️ Auto-Generated Seed Data from Excel
 * Date: 28/4/2026, 3:43:29 pm
 */

export const EXCEL_SEED = {
    ledger: [
    {
        "type": "OUT",
        "amount": 2731,
        "date": "2026-04-01T00:00:00.000Z",
        "description": "Last Month Balance ",
        "project": "",
        "category": "GENERAL",
        "from": " ",
        "mode": " ",
        "recBy": " ",
        "balance": -2731,
        "ref": "EX-ROW-4-CR"
    },
    {
        "type": "IN",
        "amount": 5000,
        "date": "2026-04-02T00:00:00.000Z",
        "description": "Receipt from Englabs IDFC",
        "project": "C-GENERAL",
        "category": "GENERAL",
        "from": "Englabs IDFC",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "balance": 2269,
        "ref": "EX-ROW-5-CR"
    },
    {
        "type": "OUT",
        "amount": 4850,
        "date": "2026-04-02T00:00:00.000Z",
        "description": "Purchase to TV Stand For delhi Expo",
        "project": "",
        "category": "EMERGENCY",
        "from": "-",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "balance": -2581,
        "ref": "EX-ROW-5-DR"
    },
    {
        "type": "IN",
        "amount": 10000,
        "date": "2026-04-02T00:00:00.000Z",
        "description": "Receipt from Englabs IDFC",
        "project": "C-GENERAL",
        "category": "GENERAL",
        "from": "Englabs IDFC",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "balance": 7419,
        "ref": "EX-ROW-6-CR"
    },
    {
        "type": "OUT",
        "amount": 850,
        "date": "2026-04-02T00:00:00.000Z",
        "description": "Purchase to Bondtite and Favikwik   For delhi Expo",
        "project": "",
        "category": "EMERGENCY",
        "from": "-",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "balance": 6569,
        "ref": "EX-ROW-6-DR"
    },
    {
        "type": "IN",
        "amount": 5000,
        "date": "2026-04-02T00:00:00.000Z",
        "description": "Receipt from Englabs IDFC",
        "project": "C-GENERAL",
        "category": "GENERAL",
        "from": "Englabs IDFC",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "balance": 11569,
        "ref": "EX-ROW-7-CR"
    },
    {
        "type": "OUT",
        "amount": 100,
        "date": "2026-04-02T00:00:00.000Z",
        "description": "UPI Rohit verma   For delhi Expo",
        "project": "",
        "category": "EMERGENCY",
        "from": "-",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "balance": 11469,
        "ref": "EX-ROW-7-DR"
    },
    {
        "type": "OUT",
        "amount": 3200,
        "date": "2026-04-02T00:00:00.000Z",
        "description": "Printer Repair Sky5 ",
        "project": "",
        "category": "MAINTENANCE",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 8269,
        "ref": "EX-ROW-8-DR"
    },
    {
        "type": "OUT",
        "amount": 250,
        "date": "2026-04-02T00:00:00.000Z",
        "description": "Porter From Raj Enterprices to Englabs For Delhi Expo. (TV STAND)",
        "project": "",
        "category": "EMERGENCY",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 8019,
        "ref": "EX-ROW-9-DR"
    },
    {
        "type": "OUT",
        "amount": 1475,
        "date": "2026-04-02T00:00:00.000Z",
        "description": "Porter From Faridabad to  Bajaj  (C5033)",
        "project": "C5033",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 6544,
        "ref": "EX-ROW-10-DR"
    },
    {
        "type": "OUT",
        "amount": 270,
        "date": "2026-04-03T00:00:00.000Z",
        "description": "Porter From Fixpro to Airport Expo Delhi",
        "project": "",
        "category": "EMERGENCY",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 6274,
        "ref": "EX-ROW-11-DR"
    },
    {
        "type": "OUT",
        "amount": 500,
        "date": "2026-04-03T00:00:00.000Z",
        "description": "Aebocode Visit Shubham Expo Delhi",
        "project": "",
        "category": "EMERGENCY",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 5774,
        "ref": "EX-ROW-12-DR"
    },
    {
        "type": "OUT",
        "amount": 70,
        "date": "2026-04-04T00:00:00.000Z",
        "description": "Purchased to Panchkula graphics (Stickers) For Delhi Expo by Devanshu  ",
        "project": "",
        "category": "EMERGENCY",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 5704,
        "ref": "EX-ROW-13-DR"
    },
    {
        "type": "OUT",
        "amount": 400,
        "date": "2026-04-04T00:00:00.000Z",
        "description": "Porter From Chennai Airport to Hankl C5008",
        "project": "C5008",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 5304,
        "ref": "EX-ROW-14-DR"
    },
    {
        "type": "OUT",
        "amount": 111,
        "date": "2026-04-04T00:00:00.000Z",
        "description": "Porter From Englabs to  Goel  C4929",
        "project": "C4929",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 5193,
        "ref": "EX-ROW-15-DR"
    },
    {
        "type": "OUT",
        "amount": 70,
        "date": "2026-04-04T00:00:00.000Z",
        "description": "Purchase to Extension Fuse C4465",
        "project": "C4465",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 5123,
        "ref": "EX-ROW-16-DR"
    },
    {
        "type": "OUT",
        "amount": 450,
        "date": "2026-04-04T00:00:00.000Z",
        "description": "Purchsed to Glash for Medical Device Expo Delhi",
        "project": "",
        "category": "EMERGENCY",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 4673,
        "ref": "EX-ROW-17-DR"
    },
    {
        "type": "OUT",
        "amount": 210,
        "date": "2026-04-06T00:00:00.000Z",
        "description": "Porter From Ultra Spark to Enertics  C4851",
        "project": "c4851",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 4463,
        "ref": "EX-ROW-18-DR"
    },
    {
        "type": "OUT",
        "amount": 180,
        "date": "2026-04-06T00:00:00.000Z",
        "description": "Porter From SK Techno to Hella Metal C5010",
        "project": "C5010",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 4283,
        "ref": "EX-ROW-19-DR"
    },
    {
        "type": "OUT",
        "amount": 320,
        "date": "2026-04-06T00:00:00.000Z",
        "description": "Porter From Fix Pro to Airport Expo Delhi",
        "project": "",
        "category": "EMERGENCY",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 3963,
        "ref": "EX-ROW-20-DR"
    },
    {
        "type": "OUT",
        "amount": 280,
        "date": "2026-04-06T00:00:00.000Z",
        "description": "Porter From Henkel telekar to Airport C5008",
        "project": "C5008",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 3683,
        "ref": "EX-ROW-21-DR"
    },
    {
        "type": "OUT",
        "amount": 1770,
        "date": "2026-04-06T00:00:00.000Z",
        "description": "Purchesed to Scrow For Delhi Expo ",
        "project": "",
        "category": "EMERGENCY",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 1913,
        "ref": "EX-ROW-22-DR"
    },
    {
        "type": "OUT",
        "amount": 400,
        "date": "2026-04-07T00:00:00.000Z",
        "description": "Porter From Rohit sir PA11 to Endureair C5098",
        "project": "C5098",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 1513,
        "ref": "EX-ROW-23-DR"
    },
    {
        "type": "OUT",
        "amount": 72,
        "date": "2026-04-07T00:00:00.000Z",
        "description": "Porter From Enertics to Englabs by Anurag C4851",
        "project": "C5098",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 1441,
        "ref": "EX-ROW-24-DR"
    },
    {
        "type": "OUT",
        "amount": 500,
        "date": "2026-04-07T00:00:00.000Z",
        "description": "RO Service + Candale Charge ",
        "project": "",
        "category": "MAINTENANCE",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 941,
        "ref": "EX-ROW-25-DR"
    },
    {
        "type": "OUT",
        "amount": 180,
        "date": "2026-04-07T00:00:00.000Z",
        "description": "Porter From Plastipack to 3D Paradise. C5108",
        "project": "C5108",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 761,
        "ref": "EX-ROW-26-DR"
    },
    {
        "type": "OUT",
        "amount": 1138,
        "date": "2026-04-07T00:00:00.000Z",
        "description": "Purchase to Delhot Expo Materials ",
        "project": "",
        "category": "EMERGENCY",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": -377,
        "ref": "EX-ROW-27-DR"
    },
    {
        "type": "OUT",
        "amount": 300,
        "date": "2026-04-07T00:00:00.000Z",
        "description": "Porter  Talekar to Pune Airport C5008",
        "project": "C5008",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": -677,
        "ref": "EX-ROW-28-DR"
    },
    {
        "type": "OUT",
        "amount": 197,
        "date": "2026-04-08T00:00:00.000Z",
        "description": "Blinkit UPI",
        "project": "",
        "category": "LOGISTICS",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": -874,
        "ref": "EX-ROW-29-DR"
    },
    {
        "type": "OUT",
        "amount": 550,
        "date": "2026-04-08T00:00:00.000Z",
        "description": "Porter From Channai to Henkel C5008",
        "project": "C5008",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": -1424,
        "ref": "EX-ROW-30-DR"
    },
    {
        "type": "OUT",
        "amount": 150,
        "date": "2026-04-08T00:00:00.000Z",
        "description": "Porter From ITL to Zirakpur C5090",
        "project": "C5090",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": -1574,
        "ref": "EX-ROW-31-DR"
    },
    {
        "type": "OUT",
        "amount": 290,
        "date": "2026-04-08T00:00:00.000Z",
        "description": "Porter From Talekar to Pune Airport C5092",
        "project": "C5092",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": -1864,
        "ref": "EX-ROW-32-DR"
    },
    {
        "type": "OUT",
        "amount": 224,
        "date": "2026-04-09T00:00:00.000Z",
        "description": "Sai Dairy Milk Last Bill Full & Final",
        "project": "",
        "category": "LOGISTICS",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": -2088,
        "ref": "EX-ROW-33-DR"
    },
    {
        "type": "OUT",
        "amount": 260,
        "date": "2026-04-09T00:00:00.000Z",
        "description": "Porter From Adoroitec to AV Machining C5014",
        "project": "",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": -2348,
        "ref": "EX-ROW-34-DR"
    },
    {
        "type": "IN",
        "amount": 5000,
        "date": "2026-04-10T00:00:00.000Z",
        "description": "Receipt from Englabs IDFC",
        "project": "C-GENERAL",
        "category": "GENERAL",
        "from": "Englabs IDFC",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "balance": 2652,
        "ref": "EX-ROW-35-CR"
    },
    {
        "type": "OUT",
        "amount": 192,
        "date": "2026-04-10T00:00:00.000Z",
        "description": "Milk 4 nos + 2 Sunday by Arjun ",
        "project": "",
        "category": "LOGISTICS",
        "from": "-",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "balance": 2460,
        "ref": "EX-ROW-35-DR"
    },
    {
        "type": "OUT",
        "amount": 704,
        "date": "2026-04-11T00:00:00.000Z",
        "description": "Blinkit UPI",
        "project": "",
        "category": "LOGISTICS",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 1756,
        "ref": "EX-ROW-36-DR"
    },
    {
        "type": "OUT",
        "amount": 350,
        "date": "2026-04-11T00:00:00.000Z",
        "description": "Porter From Channai to Henkel C5092",
        "project": "C5092",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 1406,
        "ref": "EX-ROW-37-DR"
    },
    {
        "type": "OUT",
        "amount": 400,
        "date": "2026-04-11T00:00:00.000Z",
        "description": "Porter From Sonalika Delhi to Chandigarh C5131",
        "project": "C5131",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 1006,
        "ref": "EX-ROW-38-DR"
    },
    {
        "type": "OUT",
        "amount": 130,
        "date": "2026-04-12T00:00:00.000Z",
        "description": "Porter From Tribune to Englabs ITL C5131",
        "project": "C5131",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 876,
        "ref": "EX-ROW-39-DR"
    },
    {
        "type": "OUT",
        "amount": 167,
        "date": "2026-04-13T00:00:00.000Z",
        "description": "Blinkit UPI",
        "project": "",
        "category": "LOGISTICS",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 709,
        "ref": "EX-ROW-40-DR"
    },
    {
        "type": "IN",
        "amount": 10000,
        "date": "2026-04-14T00:00:00.000Z",
        "description": "Receipt from Englabs IDFC",
        "project": "C-GENERAL",
        "category": "GENERAL",
        "from": "Englabs IDFC",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "balance": 10709,
        "ref": "EX-ROW-41-CR"
    },
    {
        "type": "OUT",
        "amount": 320,
        "date": "2026-04-14T00:00:00.000Z",
        "description": "Porter  From Excel to Marelli C4925",
        "project": "C4925",
        "category": "GENERAL",
        "from": "-",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "balance": 10389,
        "ref": "EX-ROW-41-DR"
    },
    {
        "type": "OUT",
        "amount": 2080,
        "date": "2026-04-14T00:00:00.000Z",
        "description": "Porter From Faridabad to AV Machining Pune. C5014",
        "project": "C5014",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 8309,
        "ref": "EX-ROW-42-DR"
    },
    {
        "type": "OUT",
        "amount": 390,
        "date": "2026-04-14T00:00:00.000Z",
        "description": "Porter From Plastipack to Henkel C5110",
        "project": "C5110",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 7919,
        "ref": "EX-ROW-43-DR"
    },
    {
        "type": "OUT",
        "amount": 700,
        "date": "2026-04-14T00:00:00.000Z",
        "description": "Porter From Talekar to Pune Airport C5008",
        "project": "C5008",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 7219,
        "ref": "EX-ROW-44-DR"
    },
    {
        "type": "OUT",
        "amount": 900,
        "date": "2026-04-14T00:00:00.000Z",
        "description": "Porter From Channai to Henkel C5008",
        "project": "C5008",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 6319,
        "ref": "EX-ROW-45-DR"
    },
    {
        "type": "OUT",
        "amount": 730,
        "date": "2026-04-14T00:00:00.000Z",
        "description": "Verified Paytm Merchant ",
        "project": "",
        "category": "MAINTENANCE",
        "from": "",
        "mode": "",
        "recBy": " ",
        "balance": 5589,
        "ref": "EX-ROW-46-DR"
    },
    {
        "type": "IN",
        "amount": 1000,
        "date": "2026-04-14T00:00:00.000Z",
        "description": "Receipt from Bharat sir",
        "project": "C-GENERAL",
        "category": "GENERAL",
        "from": "Bharat sir",
        "mode": "Cash",
        "recBy": "Gaurav ",
        "balance": 6589,
        "ref": "EX-ROW-47-CR"
    },
    {
        "type": "OUT",
        "amount": 720,
        "date": "2026-04-14T00:00:00.000Z",
        "description": "Purchased to White Fiber SHEET + Patch  Cash",
        "project": "",
        "category": "MAINTENANCE",
        "from": "-",
        "mode": "Cash",
        "recBy": "Gaurav ",
        "balance": 5869,
        "ref": "EX-ROW-47-DR"
    },
    {
        "type": "OUT",
        "amount": 124,
        "date": "2026-04-14T00:00:00.000Z",
        "description": "Porter From CHD Paint to Englabs ",
        "project": "",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 5745,
        "ref": "EX-ROW-48-DR"
    },
    {
        "type": "OUT",
        "amount": 1000,
        "date": "2026-04-15T00:00:00.000Z",
        "description": "Zepto Account Transfer for  Milk etc",
        "project": "",
        "category": "LOGISTICS",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 4745,
        "ref": "EX-ROW-49-DR"
    },
    {
        "type": "OUT",
        "amount": 168,
        "date": "2026-04-16T00:00:00.000Z",
        "description": "Blinkit MILK UPI",
        "project": "",
        "category": "LOGISTICS",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 4577,
        "ref": "EX-ROW-50-DR"
    },
    {
        "type": "OUT",
        "amount": 2100,
        "date": "2026-04-16T00:00:00.000Z",
        "description": "Purchase to MDF SHEET 6MM & PATCH 3INCH & GITTI & RENT ",
        "project": "",
        "category": "MAINTENANCE",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 2477,
        "ref": "EX-ROW-51-DR"
    },
    {
        "type": "OUT",
        "amount": 30,
        "date": "2026-04-16T00:00:00.000Z",
        "description": "Purchase to Adrak Cash",
        "project": "",
        "category": "LOGISTICS",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 2447,
        "ref": "EX-ROW-52-DR"
    },
    {
        "type": "IN",
        "amount": 2802,
        "date": "2026-04-16T00:00:00.000Z",
        "description": "There was an error with the payment. Please check this amount and contact the Verified Accounts team.",
        "project": "",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 5249,
        "ref": "EX-ROW-53-CR"
    },
    {
        "type": "OUT",
        "amount": 1200,
        "date": "2026-04-18T00:00:00.000Z",
        "description": "Porter From Delhi to CHD C5131",
        "project": "C5131",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 4049,
        "ref": "EX-ROW-54-DR"
    },
    {
        "type": "OUT",
        "amount": 450,
        "date": "2026-04-18T00:00:00.000Z",
        "description": "Porter From Excel to Karnal C5131",
        "project": "C5131",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 3599,
        "ref": "EX-ROW-55-DR"
    },
    {
        "type": "OUT",
        "amount": 104,
        "date": "2026-04-18T00:00:00.000Z",
        "description": "Porter by devanshu ",
        "project": "",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": " ",
        "balance": 3495,
        "ref": "EX-ROW-56-DR"
    },
    {
        "type": "OUT",
        "amount": 1950,
        "date": "2026-04-18T00:00:00.000Z",
        "description": " Purchased to MDF Sheet 6MM & Patch half Inch & Rent ",
        "project": "",
        "category": "MAINTENANCE",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 1545,
        "ref": "EX-ROW-57-DR"
    },
    {
        "type": "OUT",
        "amount": 64,
        "date": "2026-04-19T00:00:00.000Z",
        "description": "Purchase to Milk (Sunday) Cash",
        "project": "",
        "category": "LOGISTICS",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 1481,
        "ref": "EX-ROW-58-DR"
    },
    {
        "type": "IN",
        "amount": 5000,
        "date": "2026-04-20T00:00:00.000Z",
        "description": "Receipt from Englabs IDFC",
        "project": "C-GENERAL",
        "category": "GENERAL",
        "from": "Englabs IDFC",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "balance": 6481,
        "ref": "EX-ROW-59-CR"
    },
    {
        "type": "OUT",
        "amount": 32,
        "date": "2026-04-20T00:00:00.000Z",
        "description": "Purchase to Milk ) Cash",
        "project": "",
        "category": "GENERAL",
        "from": "-",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "balance": 6449,
        "ref": "EX-ROW-59-DR"
    },
    {
        "type": "OUT",
        "amount": 152,
        "date": "2026-04-20T00:00:00.000Z",
        "description": "Porter From Techno to Delhi C5142",
        "project": "C5142",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 6297,
        "ref": "EX-ROW-60-DR"
    },
    {
        "type": "OUT",
        "amount": 447,
        "date": "2026-04-20T00:00:00.000Z",
        "description": "Porter From Cadqua  to Rohit C5135",
        "project": "C5135",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 5850,
        "ref": "EX-ROW-61-DR"
    },
    {
        "type": "OUT",
        "amount": 74,
        "date": "2026-04-20T00:00:00.000Z",
        "description": "Porter From Amit Bhri  to Enclosure C-….......",
        "project": "",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 5776,
        "ref": "EX-ROW-62-DR"
    },
    {
        "type": "OUT",
        "amount": 140,
        "date": "2026-04-20T00:00:00.000Z",
        "description": "Purchase to Faviquick Gel For C4950",
        "project": "C4950",
        "category": "LOGISTICS",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 5636,
        "ref": "EX-ROW-63-DR"
    },
    {
        "type": "OUT",
        "amount": 340,
        "date": "2026-04-20T00:00:00.000Z",
        "description": "Porter From Telekar to Pune Airport C5008",
        "project": "C5008",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 5296,
        "ref": "EX-ROW-64-DR"
    },
    {
        "type": "OUT",
        "amount": 157,
        "date": "2026-04-20T00:00:00.000Z",
        "description": "Porter From Industrial area phase to Englabs C4851",
        "project": "C4851",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 5139,
        "ref": "EX-ROW-65-DR"
    },
    {
        "type": "OUT",
        "amount": 145,
        "date": "2026-04-21T00:00:00.000Z",
        "description": "PORTER From Englabs  to Hella Dera  bassi C4950",
        "project": "C4950",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 4994,
        "ref": "EX-ROW-66-DR"
    },
    {
        "type": "OUT",
        "amount": 1000,
        "date": "2026-04-21T00:00:00.000Z",
        "description": "Porter From Ambala to Englabs by Indrive (Drone Survey Invoice)",
        "project": "Saha Drone Survey",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 3994,
        "ref": "EX-ROW-67-DR"
    },
    {
        "type": "OUT",
        "amount": 800,
        "date": "2026-04-21T00:00:00.000Z",
        "description": "Porter FromChannai Airport to Henkel C5008",
        "project": "C5008",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 3194,
        "ref": "EX-ROW-68-DR"
    },
    {
        "type": "OUT",
        "amount": 13,
        "date": "2026-04-21T00:00:00.000Z",
        "description": "Porter From Englabs to Menthosa C5133",
        "project": "C5133",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 3181,
        "ref": "EX-ROW-69-DR"
    },
    {
        "type": "OUT",
        "amount": 120,
        "date": "2026-04-21T00:00:00.000Z",
        "description": "Porter From Englabs to Menthosa C5133",
        "project": "C5133",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 3061,
        "ref": "EX-ROW-70-DR"
    },
    {
        "type": "OUT",
        "amount": 345,
        "date": "2026-04-21T00:00:00.000Z",
        "description": "Porter From Noida to gurugram C5144",
        "project": "C5144",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 2716,
        "ref": "EX-ROW-71-DR"
    },
    {
        "type": "OUT",
        "amount": 210,
        "date": "2026-04-22T00:00:00.000Z",
        "description": "Blinkit UPI",
        "project": "",
        "category": "LOGISTICS",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 2506,
        "ref": "EX-ROW-72-DR"
    },
    {
        "type": "OUT",
        "amount": 1300,
        "date": "2026-04-22T00:00:00.000Z",
        "description": "Porter From Delhi to Chandigarh C4922 & 4967",
        "project": "C4922 &4967",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "Gaurav ",
        "balance": 1206,
        "ref": "EX-ROW-73-DR"
    },
    {
        "type": "IN",
        "amount": 500,
        "date": "2026-04-23T00:00:00.000Z",
        "description": "Receipt from Kabadi ",
        "project": "C-GENERAL",
        "category": "GENERAL",
        "from": "Kabadi ",
        "mode": "Cash",
        "recBy": "Englabs Indusand",
        "balance": 1706,
        "ref": "EX-ROW-74-CR"
    },
    {
        "type": "OUT",
        "amount": 127,
        "date": "2026-04-23T00:00:00.000Z",
        "description": "Porter From Englabs to Aebocode C4922",
        "project": "C4922",
        "category": "GENERAL",
        "from": "-",
        "mode": "Cash",
        "recBy": "Englabs Indusand",
        "balance": 1579,
        "ref": "EX-ROW-74-DR"
    },
    {
        "type": "OUT",
        "amount": 190,
        "date": "2026-04-23T00:00:00.000Z",
        "description": "Porter From Excel Faridabad C5138",
        "project": "C5138",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 1389,
        "ref": "EX-ROW-75-DR"
    },
    {
        "type": "OUT",
        "amount": 82,
        "date": "2026-04-24T00:00:00.000Z",
        "description": "Zepto UPI",
        "project": "",
        "category": "LOGISTICS",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 1307,
        "ref": "EX-ROW-76-DR"
    },
    {
        "type": "OUT",
        "amount": 650,
        "date": "2026-04-24T00:00:00.000Z",
        "description": "Porter From Faridabad to HC Robotics C5138",
        "project": "",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 657,
        "ref": "EX-ROW-77-DR"
    },
    {
        "type": "OUT",
        "amount": 451,
        "date": "2026-04-24T00:00:00.000Z",
        "description": "Porter From Cadqua to Orient C…........",
        "project": "",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": 206,
        "ref": "EX-ROW-78-DR"
    },
    {
        "type": "OUT",
        "amount": 600,
        "date": "2026-04-24T00:00:00.000Z",
        "description": "Porter From Cadqua to Henjel C5154",
        "project": "C5154",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": -394,
        "ref": "EX-ROW-79-DR"
    },
    {
        "type": "OUT",
        "amount": 128,
        "date": "2026-04-25T00:00:00.000Z",
        "description": "Zepto UPI",
        "project": "",
        "category": "LOGISTICS",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": -522,
        "ref": "EX-ROW-80-DR"
    },
    {
        "type": "OUT",
        "amount": 183,
        "date": "2026-04-27T00:00:00.000Z",
        "description": "Zepto UPI",
        "project": "",
        "category": "LOGISTICS",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": -705,
        "ref": "EX-ROW-81-DR"
    },
    {
        "type": "OUT",
        "amount": 656,
        "date": "1899-12-30T00:00:00.000Z",
        "description": "Labat Asia Vist Shubham ,",
        "project": "",
        "category": "EMERGENCY",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": -1361,
        "ref": "EX-ROW-82-DR"
    },
    {
        "type": "OUT",
        "amount": 1000,
        "date": "1899-12-30T00:00:00.000Z",
        "description": "Zepto Wallet ",
        "project": "",
        "category": "LOGISTICS",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": -2361,
        "ref": "EX-ROW-83-DR"
    },
    {
        "type": "OUT",
        "amount": 271,
        "date": "1899-12-30T00:00:00.000Z",
        "description": "Purchased to Handtowel For Washrrom 2nos",
        "project": "",
        "category": "LOGISTICS",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": -2632,
        "ref": "EX-ROW-84-DR"
    },
    {
        "type": "OUT",
        "amount": 656,
        "date": "1899-12-30T00:00:00.000Z",
        "description": "cash amount",
        "project": "",
        "category": "GENERAL",
        "from": "",
        "mode": "",
        "recBy": "",
        "balance": -3288,
        "ref": "EX-ROW-85-DR"
    }
],
    siteCashRows: [
    {
        "date": "2026-04-01T00:00:00.000Z",
        "from": " ",
        "mode": " ",
        "recBy": " ",
        "desc": "Last Month Balance ",
        "cr": -2731,
        "dr": 0,
        "balance": -2731,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-02T00:00:00.000Z",
        "from": "Englabs IDFC",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "desc": "Purchase to TV Stand For delhi Expo",
        "cr": 5000,
        "dr": 4850,
        "balance": -2581,
        "maintenance": 0,
        "emergency": 4850,
        "logi": 0,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-02T00:00:00.000Z",
        "from": "Englabs IDFC",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "desc": "Purchase to Bondtite and Favikwik   For delhi Expo",
        "cr": 10000,
        "dr": 850,
        "balance": 6569,
        "maintenance": 0,
        "emergency": 850,
        "logi": 0,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-02T00:00:00.000Z",
        "from": "Englabs IDFC",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "desc": "UPI Rohit verma   For delhi Expo",
        "cr": 5000,
        "dr": 100,
        "balance": 11469,
        "maintenance": 0,
        "emergency": 100,
        "logi": 0,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-02T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Printer Repair Sky5 ",
        "cr": 0,
        "dr": 3200,
        "balance": 8269,
        "maintenance": 3200,
        "emergency": 0,
        "logi": 0,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-02T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Raj Enterprices to Englabs For Delhi Expo. (TV STAND)",
        "cr": 0,
        "dr": 250,
        "balance": 8019,
        "maintenance": 0,
        "emergency": 250,
        "logi": 0,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-02T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Faridabad to  Bajaj  (C5033)",
        "cr": 0,
        "dr": 1475,
        "balance": 6544,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 1475,
        "projectId": "C5033",
        "budget": 3000,
        "profit": 1525,
        "remarks": ""
    },
    {
        "date": "2026-04-03T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Fixpro to Airport Expo Delhi",
        "cr": 0,
        "dr": 270,
        "balance": 6274,
        "maintenance": 0,
        "emergency": 270,
        "logi": 0,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-03T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Aebocode Visit Shubham Expo Delhi",
        "cr": 0,
        "dr": 500,
        "balance": 5774,
        "maintenance": 0,
        "emergency": 500,
        "logi": 0,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-04T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Purchased to Panchkula graphics (Stickers) For Delhi Expo by Devanshu  ",
        "cr": 0,
        "dr": 70,
        "balance": 5704,
        "maintenance": 0,
        "emergency": 70,
        "logi": 0,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": " "
    },
    {
        "date": "2026-04-04T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Chennai Airport to Hankl C5008",
        "cr": 0,
        "dr": 400,
        "balance": 5304,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 400,
        "projectId": "C5008",
        "budget": 23000,
        "profit": 19870,
        "remarks": ""
    },
    {
        "date": "2026-04-04T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Englabs to  Goel  C4929",
        "cr": 0,
        "dr": 111,
        "balance": 5193,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 111,
        "projectId": "C4929",
        "budget": 500,
        "profit": 389,
        "remarks": ""
    },
    {
        "date": "2026-04-04T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Purchase to Extension Fuse C4465",
        "cr": 0,
        "dr": 70,
        "balance": 5123,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 70,
        "projectId": "C4465",
        "budget": 0,
        "profit": 70,
        "remarks": ""
    },
    {
        "date": "2026-04-04T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Purchsed to Glash for Medical Device Expo Delhi",
        "cr": 0,
        "dr": 450,
        "balance": 4673,
        "maintenance": 0,
        "emergency": 450,
        "logi": 0,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-06T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Ultra Spark to Enertics  C4851",
        "cr": 0,
        "dr": 210,
        "balance": 4463,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 210,
        "projectId": "c4851",
        "budget": 2000,
        "profit": 1790,
        "remarks": ""
    },
    {
        "date": "2026-04-06T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From SK Techno to Hella Metal C5010",
        "cr": 0,
        "dr": 180,
        "balance": 4283,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 180,
        "projectId": "C5010",
        "budget": 4000,
        "profit": 3820,
        "remarks": ""
    },
    {
        "date": "2026-04-06T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Fix Pro to Airport Expo Delhi",
        "cr": 0,
        "dr": 320,
        "balance": 3963,
        "maintenance": 0,
        "emergency": 320,
        "logi": 0,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-06T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Henkel telekar to Airport C5008",
        "cr": 0,
        "dr": 280,
        "balance": 3683,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 280,
        "projectId": "C5008",
        "budget": null,
        "profit": null,
        "remarks": ""
    },
    {
        "date": "2026-04-06T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Purchesed to Scrow For Delhi Expo ",
        "cr": 0,
        "dr": 1770,
        "balance": 1913,
        "maintenance": 0,
        "emergency": 1770,
        "logi": 0,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-07T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Rohit sir PA11 to Endureair C5098",
        "cr": 0,
        "dr": 400,
        "balance": 1513,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 400,
        "projectId": "C5098",
        "budget": 1700,
        "profit": 1228,
        "remarks": ""
    },
    {
        "date": "2026-04-07T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Enertics to Englabs by Anurag C4851",
        "cr": 0,
        "dr": 72,
        "balance": 1441,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 72,
        "projectId": "C5098",
        "budget": null,
        "profit": null,
        "remarks": ""
    },
    {
        "date": "2026-04-07T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "RO Service + Candale Charge ",
        "cr": 0,
        "dr": 500,
        "balance": 941,
        "maintenance": 500,
        "emergency": 0,
        "logi": 0,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-07T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Plastipack to 3D Paradise. C5108",
        "cr": 0,
        "dr": 180,
        "balance": 761,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 180,
        "projectId": "C5108",
        "budget": 2000,
        "profit": 1820,
        "remarks": ""
    },
    {
        "date": "2026-04-07T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Purchase to Delhot Expo Materials ",
        "cr": 0,
        "dr": 1138,
        "balance": -377,
        "maintenance": 0,
        "emergency": 1138,
        "logi": 0,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-07T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter  Talekar to Pune Airport C5008",
        "cr": 0,
        "dr": 300,
        "balance": -677,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 300,
        "projectId": "C5008",
        "budget": null,
        "profit": null,
        "remarks": ""
    },
    {
        "date": "2026-04-08T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Blinkit UPI",
        "cr": 0,
        "dr": 197,
        "balance": -874,
        "maintenance": 0,
        "emergency": 0,
        "logi": 197,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-08T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Channai to Henkel C5008",
        "cr": 0,
        "dr": 550,
        "balance": -1424,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 550,
        "projectId": "C5008",
        "budget": null,
        "profit": null,
        "remarks": ""
    },
    {
        "date": "2026-04-08T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From ITL to Zirakpur C5090",
        "cr": 0,
        "dr": 150,
        "balance": -1574,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 150,
        "projectId": "C5090",
        "budget": 2000,
        "profit": 1850,
        "remarks": ""
    },
    {
        "date": "2026-04-08T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Talekar to Pune Airport C5092",
        "cr": 0,
        "dr": 290,
        "balance": -1864,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 290,
        "projectId": "C5092",
        "budget": 5600,
        "profit": 4960,
        "remarks": ""
    },
    {
        "date": "2026-04-09T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Sai Dairy Milk Last Bill Full & Final",
        "cr": 0,
        "dr": 224,
        "balance": -2088,
        "maintenance": 0,
        "emergency": 0,
        "logi": 224,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-09T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Adoroitec to AV Machining C5014",
        "cr": 0,
        "dr": 260,
        "balance": -2348,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-10T00:00:00.000Z",
        "from": "Englabs IDFC",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "desc": "Milk 4 nos + 2 Sunday by Arjun ",
        "cr": 5000,
        "dr": 192,
        "balance": 2460,
        "maintenance": 0,
        "emergency": 0,
        "logi": 192,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-11T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Blinkit UPI",
        "cr": 0,
        "dr": 704,
        "balance": 1756,
        "maintenance": 0,
        "emergency": 0,
        "logi": 704,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-11T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Channai to Henkel C5092",
        "cr": 0,
        "dr": 350,
        "balance": 1406,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 350,
        "projectId": "C5092",
        "budget": null,
        "profit": null,
        "remarks": ""
    },
    {
        "date": "2026-04-11T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Sonalika Delhi to Chandigarh C5131",
        "cr": 0,
        "dr": 400,
        "balance": 1006,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 400,
        "projectId": "C5131",
        "budget": 1500,
        "profit": 1100,
        "remarks": ""
    },
    {
        "date": "2026-04-12T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Tribune to Englabs ITL C5131",
        "cr": 0,
        "dr": 130,
        "balance": 876,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 130,
        "projectId": "C5131",
        "budget": null,
        "profit": null,
        "remarks": ""
    },
    {
        "date": "2026-04-13T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Blinkit UPI",
        "cr": 0,
        "dr": 167,
        "balance": 709,
        "maintenance": 0,
        "emergency": 0,
        "logi": 167,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-14T00:00:00.000Z",
        "from": "Englabs IDFC",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "desc": "Porter  From Excel to Marelli C4925",
        "cr": 10000,
        "dr": 320,
        "balance": 10389,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 320,
        "projectId": "C4925",
        "budget": 2000,
        "profit": -1680,
        "remarks": ""
    },
    {
        "date": "2026-04-14T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Faridabad to AV Machining Pune. C5014",
        "cr": 0,
        "dr": 2080,
        "balance": 8309,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 2080,
        "projectId": "C5014",
        "budget": 3000,
        "profit": 920,
        "remarks": ""
    },
    {
        "date": "2026-04-14T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Plastipack to Henkel C5110",
        "cr": 0,
        "dr": 390,
        "balance": 7919,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 390,
        "projectId": "C5110",
        "budget": 2000,
        "profit": 1610,
        "remarks": ""
    },
    {
        "date": "2026-04-14T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Talekar to Pune Airport C5008",
        "cr": 0,
        "dr": 700,
        "balance": 7219,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 700,
        "projectId": "C5008",
        "budget": null,
        "profit": null,
        "remarks": ""
    },
    {
        "date": "2026-04-14T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Channai to Henkel C5008",
        "cr": 0,
        "dr": 900,
        "balance": 6319,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 900,
        "projectId": "C5008",
        "budget": null,
        "profit": null,
        "remarks": ""
    },
    {
        "date": "2026-04-14T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": " ",
        "desc": "Verified Paytm Merchant ",
        "cr": 0,
        "dr": 730,
        "balance": 5589,
        "maintenance": 730,
        "emergency": 0,
        "logi": 0,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-14T00:00:00.000Z",
        "from": "Bharat sir",
        "mode": "Cash",
        "recBy": "Gaurav ",
        "desc": "Purchased to White Fiber SHEET + Patch  Cash",
        "cr": 1000,
        "dr": 720,
        "balance": 5869,
        "maintenance": 720,
        "emergency": 0,
        "logi": 0,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-14T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From CHD Paint to Englabs ",
        "cr": 0,
        "dr": 124,
        "balance": 5745,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-15T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Zepto Account Transfer for  Milk etc",
        "cr": 0,
        "dr": 1000,
        "balance": 4745,
        "maintenance": 0,
        "emergency": 0,
        "logi": 1000,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-16T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Blinkit MILK UPI",
        "cr": 0,
        "dr": 168,
        "balance": 4577,
        "maintenance": 0,
        "emergency": 0,
        "logi": 168,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-16T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Purchase to MDF SHEET 6MM & PATCH 3INCH & GITTI & RENT ",
        "cr": 0,
        "dr": 2100,
        "balance": 2477,
        "maintenance": 2100,
        "emergency": 0,
        "logi": 0,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-16T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Purchase to Adrak Cash",
        "cr": 0,
        "dr": 30,
        "balance": 2447,
        "maintenance": 0,
        "emergency": 0,
        "logi": 30,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-16T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "There was an error with the payment. Please check this amount and contact the Verified Accounts team.",
        "cr": 2802,
        "dr": 0,
        "balance": 5249,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-18T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Delhi to CHD C5131",
        "cr": 0,
        "dr": 1200,
        "balance": 4049,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 1200,
        "projectId": "C5131",
        "budget": null,
        "profit": null,
        "remarks": ""
    },
    {
        "date": "2026-04-18T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Excel to Karnal C5131",
        "cr": 0,
        "dr": 450,
        "balance": 3599,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 450,
        "projectId": "C5131",
        "budget": null,
        "profit": null,
        "remarks": ""
    },
    {
        "date": "2026-04-18T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": " ",
        "desc": "Porter by devanshu ",
        "cr": 0,
        "dr": 104,
        "balance": 3495,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-18T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": " Purchased to MDF Sheet 6MM & Patch half Inch & Rent ",
        "cr": 0,
        "dr": 1950,
        "balance": 1545,
        "maintenance": 1950,
        "emergency": 0,
        "logi": 0,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-19T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Purchase to Milk (Sunday) Cash",
        "cr": 0,
        "dr": 64,
        "balance": 1481,
        "maintenance": 0,
        "emergency": 0,
        "logi": 64,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-20T00:00:00.000Z",
        "from": "Englabs IDFC",
        "mode": "NEFT",
        "recBy": "Englabs Indusand",
        "desc": "Purchase to Milk ) Cash",
        "cr": 5000,
        "dr": 32,
        "balance": 6449,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-20T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Techno to Delhi C5142",
        "cr": 0,
        "dr": 152,
        "balance": 6297,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 152,
        "projectId": "C5142",
        "budget": 2000,
        "profit": -1848,
        "remarks": ""
    },
    {
        "date": "2026-04-20T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Cadqua  to Rohit C5135",
        "cr": 0,
        "dr": 447,
        "balance": 5850,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 447,
        "projectId": "C5135",
        "budget": 0,
        "profit": 447,
        "remarks": ""
    },
    {
        "date": "2026-04-20T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Amit Bhri  to Enclosure C-….......",
        "cr": 0,
        "dr": 74,
        "balance": 5776,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 74,
        "projectId": "",
        "budget": 0,
        "profit": 74,
        "remarks": ""
    },
    {
        "date": "2026-04-20T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Purchase to Faviquick Gel For C4950",
        "cr": 0,
        "dr": 140,
        "balance": 5636,
        "maintenance": 0,
        "emergency": 0,
        "logi": 140,
        "projDr": 0,
        "projectId": "C4950",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-20T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Telekar to Pune Airport C5008",
        "cr": 0,
        "dr": 340,
        "balance": 5296,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 340,
        "projectId": "C5008",
        "budget": null,
        "profit": null,
        "remarks": ""
    },
    {
        "date": "2026-04-20T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Industrial area phase to Englabs C4851",
        "cr": 0,
        "dr": 157,
        "balance": 5139,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 157,
        "projectId": "C4851",
        "budget": 0,
        "profit": 157,
        "remarks": ""
    },
    {
        "date": "2026-04-21T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "PORTER From Englabs  to Hella Dera  bassi C4950",
        "cr": 0,
        "dr": 145,
        "balance": 4994,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 145,
        "projectId": "C4950",
        "budget": 0,
        "profit": 145,
        "remarks": ""
    },
    {
        "date": "2026-04-21T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Ambala to Englabs by Indrive (Drone Survey Invoice)",
        "cr": 0,
        "dr": 1000,
        "balance": 3994,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 1000,
        "projectId": "Saha Drone Survey",
        "budget": 0,
        "profit": 1000,
        "remarks": ""
    },
    {
        "date": "2026-04-21T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter FromChannai Airport to Henkel C5008",
        "cr": 0,
        "dr": 800,
        "balance": 3194,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 800,
        "projectId": "C5008",
        "budget": 0,
        "profit": 800,
        "remarks": ""
    },
    {
        "date": "2026-04-21T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Englabs to Menthosa C5133",
        "cr": 0,
        "dr": 13,
        "balance": 3181,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 13,
        "projectId": "C5133",
        "budget": 0,
        "profit": 13,
        "remarks": ""
    },
    {
        "date": "2026-04-21T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Englabs to Menthosa C5133",
        "cr": 0,
        "dr": 120,
        "balance": 3061,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 120,
        "projectId": "C5133",
        "budget": 0,
        "profit": 120,
        "remarks": ""
    },
    {
        "date": "2026-04-21T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Noida to gurugram C5144",
        "cr": 0,
        "dr": 345,
        "balance": 2716,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 345,
        "projectId": "C5144",
        "budget": 0,
        "profit": 345,
        "remarks": ""
    },
    {
        "date": "2026-04-22T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Blinkit UPI",
        "cr": 0,
        "dr": 210,
        "balance": 2506,
        "maintenance": 0,
        "emergency": 0,
        "logi": 210,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-22T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "Gaurav ",
        "desc": "Porter From Delhi to Chandigarh C4922 & 4967",
        "cr": 0,
        "dr": 1300,
        "balance": 1206,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 1300,
        "projectId": "C4922 &4967",
        "budget": 0,
        "profit": 1300,
        "remarks": ""
    },
    {
        "date": "2026-04-23T00:00:00.000Z",
        "from": "Kabadi ",
        "mode": "Cash",
        "recBy": "Englabs Indusand",
        "desc": "Porter From Englabs to Aebocode C4922",
        "cr": 500,
        "dr": 127,
        "balance": 1579,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 127,
        "projectId": "C4922",
        "budget": 0,
        "profit": 127,
        "remarks": ""
    },
    {
        "date": "2026-04-23T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Excel Faridabad C5138",
        "cr": 0,
        "dr": 190,
        "balance": 1389,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 190,
        "projectId": "C5138",
        "budget": 0,
        "profit": 190,
        "remarks": ""
    },
    {
        "date": "2026-04-24T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Zepto UPI",
        "cr": 0,
        "dr": 82,
        "balance": 1307,
        "maintenance": 0,
        "emergency": 0,
        "logi": 82,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-24T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Faridabad to HC Robotics C5138",
        "cr": 0,
        "dr": 650,
        "balance": 657,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 650,
        "projectId": "",
        "budget": 0,
        "profit": 650,
        "remarks": ""
    },
    {
        "date": "2026-04-24T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Cadqua to Orient C…........",
        "cr": 0,
        "dr": 451,
        "balance": 206,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 451,
        "projectId": "",
        "budget": 0,
        "profit": 451,
        "remarks": ""
    },
    {
        "date": "2026-04-24T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Porter From Cadqua to Henjel C5154",
        "cr": 0,
        "dr": 600,
        "balance": -394,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 600,
        "projectId": "C5154",
        "budget": 0,
        "profit": 600,
        "remarks": ""
    },
    {
        "date": "2026-04-25T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Zepto UPI",
        "cr": 0,
        "dr": 128,
        "balance": -522,
        "maintenance": 0,
        "emergency": 0,
        "logi": 128,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "2026-04-27T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Zepto UPI",
        "cr": 0,
        "dr": 183,
        "balance": -705,
        "maintenance": 0,
        "emergency": 0,
        "logi": 183,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "1899-12-30T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Labat Asia Vist Shubham ,",
        "cr": 0,
        "dr": 656,
        "balance": -1361,
        "maintenance": 0,
        "emergency": 656,
        "logi": 0,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": "as per New Projects Visit"
    },
    {
        "date": "1899-12-30T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Zepto Wallet ",
        "cr": 0,
        "dr": 1000,
        "balance": -2361,
        "maintenance": 0,
        "emergency": 0,
        "logi": 1000,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "1899-12-30T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "Purchased to Handtowel For Washrrom 2nos",
        "cr": 0,
        "dr": 271,
        "balance": -2632,
        "maintenance": 0,
        "emergency": 0,
        "logi": 271,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    },
    {
        "date": "1899-12-30T00:00:00.000Z",
        "from": "",
        "mode": "",
        "recBy": "",
        "desc": "cash amount",
        "cr": 0,
        "dr": 656,
        "balance": -3288,
        "maintenance": 0,
        "emergency": 0,
        "logi": 0,
        "projDr": 0,
        "projectId": "",
        "budget": 0,
        "profit": 0,
        "remarks": ""
    }
],
    discoveredItems: [
    {
        "name": "TV Stand",
        "qty": 1,
        "rate": 4850
    },
    {
        "name": "Bondtite Adhesive",
        "qty": 1,
        "rate": 425
    },
    {
        "name": "Favikwik Adhesive",
        "qty": 2,
        "rate": 282.5
    },
    {
        "name": "Panchkula graphics",
        "qty": 1,
        "rate": 70
    },
    {
        "name": "Extension Fuse",
        "qty": 1,
        "rate": 70
    },
    {
        "name": "Delhot Expo Materials",
        "qty": 1,
        "rate": 1138
    },
    {
        "name": "Dairy/Office Supplies",
        "qty": 8,
        "rate": 189
    },
    {
        "name": "White Fiber SHEET + Patch  Cash",
        "qty": 1,
        "rate": 720
    },
    {
        "name": "MDF Sheets (6mm/10mm)",
        "qty": 2,
        "rate": 2025
    },
    {
        "name": "Adrak Cash",
        "qty": 1,
        "rate": 30
    },
    {
        "name": "Office Essentials",
        "qty": 1,
        "rate": 1000
    },
    {
        "name": "Handtowel",
        "qty": 1,
        "rate": 271
    }
],
    discoveredProjects: [
    "C5033",
    "C5008",
    "C4929",
    "C4465",
    "c4851",
    "C5010",
    "C5098",
    "C5108",
    "C5090",
    "C5092",
    "C5131",
    "C4925",
    "C5014",
    "C5110",
    "C5142",
    "C5135",
    "C4950",
    "C4851",
    "Saha Drone Survey",
    "C5133",
    "C5144",
    "C4922 &4967",
    "C4922",
    "C5138",
    "C5154"
]
};
